routes/web.php
	'as' => 'mixed.heavy.waste.pricing.form',
	'uses' => 'MixedHeavyWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('2/showForm/{status}/{message}',[
	'as' => 'mixed.heavy.waste.form',
	'uses' => 'MixedHeavyWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('2/editBinServicePrice', 'MixedHeavyWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('2/resetPricing/{bintype}/{binsize}', 'MixedHeavyWaste@resetRates')->middleware('checkRole:1,2');

/****** CLEAN FILLS SCHEDULE ***/
Route::get('/clean_fills_schedule', 'CleanFills@index')->middleware('checkRole:1,2');

Route::get('/clean_fills_schedule/{status}/{message}',[
	'as' => 'clean.fills.schedule',
	'uses' => 'CleanFills@showResult'
])->middleware('checkRole:1,2');

Route::get('3/calendarOffset/{offset}',[
	'uses' => 'CleanFills@showResult'
])->middleware('checkRole:1,2');

Route::get('3/{binsize}/calendarOffset/{offset}',[
	'uses' => 'CleanFills@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/3', 'CleanFills@editMiscDetail')->middleware('checkRole:1,2');
Route::post('3/editNonDeliveryDays', 'CleanFills@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('3/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'clean.fills.pricing.form',
	'uses' => 'CleanFills@showForm'
])->middleware('checkRole:1,2');

Route::get('3/showForm/{status}/{message}',[
	'as' => 'clean.fills.waste.form',
	'uses' => 'CleanFills@showFormResult'
])->middleware('checkRole:1,2');

Route::post('3/editBinServicePrice', 'CleanFills@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('3/resetPricing/{bintype}/{binsize}', 'CleanFills@resetRates')->middleware('checkRole:1,2');

/****** GREEN WASTE SCHEDULE ***/
Route::get('/green_waste_schedule',  [
	'as' => 'green_waste',
	'uses' => 'GreenWaste@index'
])->middleware('checkRole:1,2');

Route::get('/green_waste_schedule/{status}/{message}',[
	'as' => 'green.waste.schedule',
	'uses' => 'GreenWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('4/calendarOffset/{offset}',[
	'uses' => 'GreenWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('4/{binsize}/calendarOffset/{offset}',[
	'uses' => 'GreenWaste@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/4', 'GreenWaste@editMiscDetail')->middleware('checkRole:1,2');
Route::post('4/editNonDeliveryDays', 'GreenWaste@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('4/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'green.waste.pricing.form',
	'uses' => 'GreenWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('4/showForm/{status}/{message}',[
	'as' => 'green.waste.form',
	'uses' => 'GreenWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('4/editBinServicePrice', 'GreenWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('4/resetPricing/{bintype}/{binsize}', 'GreenWaste@resetRates')->middleware('checkRole:1,2');

/****** DIRT WASTE SCHEDULE ***/
Route::get('/dirt_waste_schedule', [
	'as' => 'dirt_waste',
	'uses' => 'DirtWaste@index'
])->middleware('checkRole:1,2');

Route::get('/dirt_waste_schedule/{status}/{message}',[
	'as' => 'dirt.waste.schedule',
	'uses' => 'DirtWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('5/calendarOffset/{offset}',[
	'uses' => 'DirtWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('5/{binsize}/calendarOffset/{offset}',[
	'uses' => 'DirtWaste@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/5', 'DirtWaste@editMiscDetail')->middleware('checkRole:1,2');
Route::post('5/editNonDeliveryDays', 'DirtWaste@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('5/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'dirt.waste.pricing.form',
	'uses' => 'DirtWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('5/showForm/{status}/{message}',[
	'as' => 'dirt.waste.form',
	'uses' => 'DirtWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('5/editBinServicePrice', 'DirtWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('5/resetPricing/{bintype}/{binsize}', 'DirtWaste@resetRates')->middleware('checkRole:1,2');

/****** ORDER RECEIPTING  ***/
Route::get('/order_receipt', [
	'as' => 'order.receipt',
	'uses' => 'ReceiptOrder@index'
])->middleware('checkRole:1,2');

Route::get('manage_order/','adminController@manage_order_view')->name('supplier_supplies')->middleware('checkRole:1');
Route::get('all_supplier_order/','adminController@all_order_view')->name('all_supplier_supplies')->middleware('checkRole:1');
Route::get('all_supplier_order_date/','adminController@all_order_view_date')->name('all_supplier_supplies_date')->middleware('checkRole:1');
Route::get('/manage_order/{idSupplier}',[
	'as' => 'supplier_supplies_result',
	'uses' => 'adminController@fetch_supplier_order_status'
])->middleware('checkRole:1');
Route::post('see_supplies_by_supplier/','adminController@fetch_supplier_order')->name('fetch_all_order_supplies')->middleware('checkRole:1');
Route::post('see_supplies_all/','adminController@fetch_all_supplier')->name('fetch_all_supplier')->middleware('checkRole:1');
Route::post('see_supplies_all_order_date/','adminController@fetch_all_supplier_order')->name('fetch_all_supplier_date')->middleware('checkRole:1');
Route::post('change_order_status/', 'adminController@update_order_status')->name('update_order_status')->middleware('checkRole:1,2');

Route::post('change_order_status_by_user/', 'ReceiptOrder@update_order_status')->name('update_order_status_by_user')->middleware('checkRole:1,2');

Route::get('order_detail/{orderref}/{idSupplier}/{idCustomer}/{idBinType}/{idBinService}','adminController@order_detail')->name('detailed_order')->middleware('checkRole:1,2');

/*** PAYPAL ***/
//Route::get('paymentdetails/{idpaymenttemp}','PaypalController@addPayment')->name('addPayment');
//Route::post('paypal', 'PaypalController@postPaymentWithpaypal')->name('paypal');
//Route::get('paypal','PaypalController@getPaymentStatus')->name('status');
//Route::get('paymentstatus','PaypalController@paymentStatus')->name('paymentstatus');
//Route::get('away','PaypalController@away')->name('away');
Route::get('paymentdetails/{idpaymenttemp}','scnpayment@addPayment')->name('addPayment');
Route::post('payment', 'scnpayment@post_details')->name('payment');
Route::get('paymenthost','scnpayment@scn_iframe')->name('host');
Route::get('payment_engagement/','scnpayment@scn_iframe_response')->name('engagement');
Route::get('payment_status/','scnpayment@paymentStatus')->name('payment_status');
Route::post('ajax_hash_post/','scnpayment@ajax_hash_post')->name('ajax_hash_post');
Route::get('away','scnpayment@away')->name('away');

/** INVOICE **/
Route::get('orderservice/{idorderservice}','ReceiptOrder@orderservicedetail')->name('orderdetails')->middleware('checkRole:1,2');
Route::get('test_invoice_mail/{idorderservice}','ReceiptOrder@test_mail')->name('test_mail')->middleware('checkRole:1,2');
Route::get('export/pdf/{idorderservice}','ReceiptOrder@pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');
Route::get('export/invoice/pdf/{idorderservice}','ReceiptOrder@invoice_pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');

/** ADMIN SUPER POWER TECHNIQUE **/
Route::get('manage_user/','adminController@usermanagement_view')->name('user_management')->middleware('checkRole:1');
Route::get('approve_user/{idUser}','adminController@aprroveuser')->name('approve_user')->middleware('checkRole:1');

Route::get('active_user/','adminController@activeuser_view')->name('active_user')->middleware('checkRole:1');
Route::get('kick_user/{idUser}','adminController@kickuser')->name('kick_user')->middleware('checkRole:1');

Route::get('banned_user/','adminController@banuser_view')->name('banned_user')->middleware('checkRole:1');
Route::get('reactivate_user/{idUser}','adminController@reactivate_user')->name('reactivate_user')->middleware('checkRole:1');

Route::prefix('booking-fees')
	->name('booking-fees.')
	->middleware('checkRole:1')
	->group(function () {

		Route::get('/', 'BookingFeeSettingController@index')
			->name('index');

		Route::get('/edit/{tblsupplier}', 'BookingFeeSettingController@edit')
			->name('edit');

		Route::post('/update/{tblsupplier}', 'BookingFeeSettingController@update')
			->name('update');

	});

/** only for jims
Route::get('approve_user/jim/{idUser}','adminController@jimapprove')->name('jimapprove')->middleware('checkRole:1');**/
/** SUMMARY **/
Route::get('manage_summary/','orderSummary@ordersummary_view')->name('summary_management')->middleware('checkRole:1');
Route::post('see_supplies_by_supplier_summary/','orderSummary@fetch_supplier_order')->name('fetch_all_order_supplies_summary')->middleware('checkRole:1');
Route::get('order_summary/export/pdf/{idSupplier}/{startDate}/{endDate}','orderSummary@pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');
Route::post('order_summary_selected/export/pdf/','orderSummary@pdfexporterselected')->name('pdfexporterselected')->middleware('checkRole:1,2');

/** BOOKING FEE **/
Route::get('booking_fee/','bookingprice@index')->name('bookingfee')->middleware('checkRole:1');
Route::get('booking_fee/{idBookingPrice}','bookingprice@edit_form')->name('edit_form')->middleware('checkRole:1');
Route::get('booking_form/','bookingprice@bookingform_view')->name('booking_form')->middleware('checkRole:1');
Route::post('edit_bookingfee/','bookingprice@edit_bookingfee')->name('edit_bookingfee')->middleware('checkRole:1');

/** MAILING EXTENSION **/
//user_registration
Route::get('mail/user/verify/{name}/{verification_code}','loginController@mail_extension')->name('mail_extension');

/** Report addiction **/
Route::get('binorder_report/','Order_Summary_BinType@order_summary_bin_view')->name('binorder_report')->middleware('checkRole:1');

/* generate payment link based on fake order */
Route::get('test-payment', 'TestPaymentController')

app/BookingFeeSetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BookingFeeSetting extends Model
{
    protected $fillable = [
        'supplier_id',
        'type',
        'amount'
    ];

    public function getAmountTextAttribute()
    {
        return ($this->type == 'fix') ? "${$this->amount}" : "{$this->amount}%";
    }
}

resources/views/pdf/orderslip.blade.php
<htmlpageheader name="page-header">
	Bin Hire Quote from Invoice {{$invoiceDetails->paymentUniqueCode}}
</htmlpageheader>
<!DOCTYPE html>
	<html>
		<head>
			 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			 <style >
				@media print {
					body{
						font-size:11px;
						line-height:1.9px;
					}
					.table-responsive{
						margin:10px 0;
						line-height:1.7;
					}
					table{
						line-height:1.7;
					}
				}
			</style>
		</head>
		<body>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr style="text-align:center">
						<td width="50%">
							<img src="{{url('assets/images/skipbin-logo_03.png')}}" />
						</td>
						<td width="50%" style="padding-left: 20px;text-align:right">
							<address style="font-style:12px;">
								Ezyskips Online<br/>
								PO Box 14 Woodvale<br/>
								6026 <br/>
								0410 704 294<br/>
								info@ezyskipsonline.com.au<br/>
								ABN : 44 331 419 402
							</address>
						</td>
					</tr>
					<tr style="text-align:center">
						<td colspan="2">
							<h3 style="text-transform:uppercase;">Order Slip </h3> <br />
							<strong style="text-transform:uppercase;">Invoice no. {{$invoiceDetails->paymentUniqueCode}}</strong><br />
							<strong><?=date('l d-m-Y', strtotime($invoiceDetails->orderDate));?></strong> </strong><br />
						</td>
					</tr>
				</table>
			</div>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr>
						<td width="50%">
							<h3 style="text-transform:uppercase;">Customer Delivery Details:</h3>
							<address style="font-style:12px;">
								{{$customerdetails->name}}<br/>
								{{$customerdetails->address}} <br/>
								{{$customerdetails->suburb}} <br/>
								{{$customerdetails->zipcode}} <br/>

								{{$customerdetails->phone}} <br/>
								{{$customerdetails->email}}
							</address>
						</td>

					</tr>
				</table>
			</div>

			<div class="table-responsive">
				<table class="table table-condensed" border="0"  width="100%" cellpadding="3">
					<tr>
						<td  width="50%" >
							<h3 style="text-transform:uppercase;">Delivery Date:</h3>
							<address style="font-style:12px;">
								<?=date('l d-m-Y', strtotime($invoiceDetails->deliveryDate));?>
							</address>
						</td>
						<td  width="50%" style="padding-left: 20px;">
							<h3 style="text-transform:uppercase;">Collection Date:</h3>
							<address style="font-style:12px;">
								<?=date('l d-m-Y', strtotime($invoiceDetails->collectionDate));?>
							</address>
						</td>
					</tr>
				</table>
			</div>

			<div class="table-responsive">
				<table class="table table-condensed" border="1" style="border:1px solid #b1b2b2;" width="100%" cellpadding="3">
					<tbody>
						<tr style="background:#005343;">
							<td colspan="3" style="color:#fff;text-align:center;text-transform:uppercase;"><strong><h3>Order summary</h3></strong></td>
						</tr>
						<tr>
							<td ><strong>Bin type</strong></td>
							<td colspan="2" >{{$binhire->name}}</td>
						</tr>
						<tr>
							<td ><strong>Bin size</strong></td>
							<td colspan="2" >{{$binhire->size}}</td>
						</tr>
						<tr>
							<td ><strong>Description</strong></td>
							<td colspan="2" >
								<?php $tags = array("strong", "b");?>
								<p><?php echo preg_replace('#<(' . implode( '|', $tags) . ')(?:[^>]+)?>.*?</\1>#s', '', $binhire->description2);?></p><br />
								<p style="color:#c40005;"><?php echo $binhire->description; ?></p>
							</td>
						</tr>

						<!--<tr>
							<td  style="text-transform:uppercase;"><strong>Bin price</strong></td>
							<td colspan="2"  style="text-transform:uppercase;">$sprintf('%1.2f',$binhire->price)</td>
						</tr>-->
						<!--<tr>
							<td><strong>GST 10%</strong></td>
							$gst = $invoiceDetails->subtotal*0.10;
							<td colspan="2">$sprintf('%1.2f',$gst)</td>
						</tr>-->
						<!--<tr>
							<td><strong>Fee</strong></td>
							<td colspan="2">- $sprintf('%1.2f',$commision)</td>
						</tr>-->
						<tr style="color:#fff;background:#005343">
							<td style="color:#fff;"><strong>Price charged</strong></td>
							<td colspan="2" style="color:#fff;">
							$<?php echo sprintf('%1.2f',$invoiceDetails->subtotal);?></td>
						</tr>
					</tbody>
				</table>
			</div>
			@if(!is_null($invoiceDetails->deliveryComments))
				<div class="table-responsive">
					<table class="table table-condensed" border="0" width="100%" cellpadding="3">
						<tr>
							<td width="50%">
								<h3 style="text-transform:uppercase;">Additional Note:</h3>
								<address  style="font-style:12px;">
									{{$invoiceDetails->deliveryComments}}
								</address>
							</td>
						</tr>
					</table>
				</div>
			@endif
		</body>
	</html>
<htmlpagefooter name="page-footer">
	{PAGENO}
</htmlpagefooter>

resources/views/pdf/ordersummary_template.blade.php
<htmlpageheader name="page-header">
	Annual Order Summary
</htmlpageheader>
<!DOCTYPE html>
	<html>
		<head>
			 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			 <style >
				@media print {
					body{
						font-size:11px;
						line-height:1.9px;
					}
					.table-responsive{
						margin:10px 0;
						line-height:1.7;
					}
					table{
						line-height:1.7;
					}
				}
			</style>
		</head>
		<body>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr >
						<td width="50%" style="text-align:left">
							<img src="{{url('assets/images/skipbin-logo_03.png')}}" />
						</td>
						<td width="50%" style="padding-left: 20px;text-align:right">
							<address style="font-style:12px;">
								Ezyskips Online<br/>
								PO Box 14 Woodvale<br/>
								6026 <br/>
								0410 704 294<br/>
								info@ezyskipsonline.com.au<br/>
							</address>
						</td>
					</tr>
				</table>
			</div>

			<div class="table-responsive">
				<table class="table table-condensed" border="0" cellpadding="3">
					<tr>
						<td>
							<h3 style="text-transform:uppercase;">Order Summary</h3> <br />
							<strong style="text-transform:uppercase;">Date:</strong> {{$startDate}} - {{$endDate}}</strong> <br />
							<strong style="text-transform:uppercase;">Supplier: {{$selected_supplierdata->name}}</strong>
						</td>
					</tr>
				</table>
			</div>

			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr>
						<td>
							<h3 style="text-transform:uppercase;">Supplier Details:</h3>
							<address >
								{{$selected_supplierdata->name}}<br/>
								{{$selected_supplierdata->email}} <br/>
								{{$selected_supplierdata->phonenumber}} <br/>
								{{$selected_supplierdata->fullAddress}} <br/>
							</address>
						</td>
					</tr>
				</table>
			</div>

			<div class="table-responsive">

				<table class="data table table-bordered" border="1" style="border:1px solid #b1b2b2;" width="100%" cellpadding="3">
					<tr class="text-center" align="center" style="color:#fff !important;background:#005343;">
						<td><strong style="color:#fff ">Order Ref</strong></td>
						<td><strong style="color:#fff ">Order Date</strong></td>
						<td><strong style="color:#fff ">Bin Type</strong></td>
						<td><strong style="color:#fff ">Bin Size</strong></td>
						<td><strong style="color:#fff ">Collection Date</strong></td>
						<td><strong style="color:#fff ">Revenue</strong></td>
					</tr>
					<tbody>
						@foreach($suppliesdata as $data)
							<tr>
								<td><a href="{{ url('/') }}/order_detail/{{$data->paymentUniqueCode}}/{{$data->idSupplier}}/{{$data->idCustomer}}/{{$data->idBinType}}/{{$data->idBinService}}">{{$data->paymentUniqueCode}}</a></td>
								<td >{{date('d-m-Y', strtotime($data->orderDate))}}</td>
								<td >{{$data->bintypename}}</td>
								<td >{{$data->binsize}}</td>
								<td >{{date('d/m/Y', strtotime($data->collectionDate))}}</td>
								<td>
									${{sprintf('%1.2f',$data->subtotal)}}
								</td>
							</tr>
						@endforeach
							<tr>
								<td colspan="5" class="text-center">
									<strong>Subtotal</strong>
								</td>
								<td>
									<strong>${{sprintf('%1.2f',$sub)}}</strong>
								</td>
							</tr>
							<tr>
								<td colspan="5" class="text-center">
									<strong>Grand Total (After deducted {{ $bookingFee->amount_text }} for Ezyskips Online)</strong>
								</td>
								<td>
									<strong>${{sprintf('%1.2f', $sub - $total_fee)}}</strong>
								</td>
							</tr>
					</tbody>
				</table>
			</div>
		</body>
	</html>
<htmlpagefooter name="page-footer">
	{PAGENO}
</htmlpagefooter>

resources/views/pdf/template.blade.php
<htmlpageheader name="page-header">
	Bin Hire Quote from Invoice {{$invoiceDetails->paymentUniqueCode}}
</htmlpageheader>
	<!DOCTYPE html>
	<html>
		<head>
			 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			 <style >
				@media print { 
					body{
						font-size:11px;
						line-height:1.9px;
					}
					.table-responsive{
						margin:10px 0;
						line-height:1.7;
					}
					table{
						line-height:1.7;
					}
				} 
				
			</style>
		</head>
		<body>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr style="text-align:center">
						<td width="50%">
							<img src="{{url('assets/images/skipbin-logo_03.png')}}" />
						</td>
						<td width="50%" style="padding-left: 20px;text-align:right">
							<address style="font-style:12px;">
								Ezyskips Online<br/>
								PO Box 14 Woodvale<br/>
								6026 <br/>
								0410 704 294<br/>
								info@ezyskipsonline.com.au<br/>
								ABN : 44 331 419 402
							</address>
						</td>
					</tr>
					<tr style="text-align:center">
						<td>
							<h3 style="text-transform:uppercase;">Tax Invoice no. {{$invoiceDetails->paymentUniqueCode}}</h3> <br />
							<strong ><?=date('l d-m-Y', strtotime($invoiceDetails->orderDate));?></strong ><br />
						</td>
					</tr>
				</table>
			</div>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" cellpadding="3">
					<tr>
						<td >
							<h3 style="text-transform:uppercase;">Customer Delivery Details:</h3>
							
							<address style="font-style:12px;">
								{{$customerdetails->name}}<br/>
								{{$customerdetails->address}}<br/>
								{{$customerdetails->suburb}} <br/>
								{{$customerdetails->zipcode}} <br/>
								{{$customerdetails->phone}} <br/>
								{{$customerdetails->email}}
							</address>
						</td>
					</tr>
				</table>
			</div>
			
			<!--<div class="table-responsive">
				<table class="table table-condensed" border="0"  width="100%">
					<tr>
						<td >
							<h5>Delivery Address:</h5>
							<address>
								<?//=$invoiceDetails->deliveryAddress;?>
							</address>
						</td>
					</tr>
				</table>
			</div>-->
			<div class="table-responsive">
				<table class="table table-condensed" border="0"  width="100%" cellpadding="3">
					<tr>
						<td  width="50%">
							<h3 style="text-transform:uppercase;">Delivery Date:</h3>
							<address style="font-style:12px;">
								<?=date('l d-m-Y', strtotime($invoiceDetails->deliveryDate));?>
							</address>
						</td>
						<td  width="50%" style="padding-left: 20px">
							<h3 style="text-transform:uppercase">Collection Date:</h3>
							<address style="font-style:12px;">
								<?=date('l d-m-Y', strtotime($invoiceDetails->collectionDate));?>
							</address>
						</td>
					</tr>
				</table>
			</div>
			<div class="table-responsive">
				<table width="100%" class="table table-condensed" border="0" cellpadding="3">
					<tr>
						<td >
							<?php //if (isset($binhireoptions->extraHireagePrice) && ($binhireoptions->extraHireagePrice > 0) && ($binhireoptions->extraHireageDays > 0)) :?>
								<!--<p><span>Charged $<?//=$binhireoptions->extraHireagePrice?> after <?//=$binhireoptions->extraHireageDays?> days hire</span></p>-->
							<?php //endif;?>
							<?php if (isset($binhireoptions->excessWeightPrice) && ($binhireoptions->excessWeightPrice > 0)) :?>
								<p style="font-style:12px;"><span><strong>First 300kg included in price. Prorata price thereafter $<?=$binhireoptions->excessWeightPrice?> per 1000kg. </span></strong></p>
							<?php endif;?>
						</td>
					</tr>
				</table>
			</div>
			<div class="table-responsive">
				<table class="table table-condensed" border="1" style="border:0.5px solid #b1b2b2;" width="100%" cellpadding="3">
					<tbody>
						<tr style="background:#005343;text-align:center">
							<td colspan="3" style="color:#fff;text-align:center;text-transform:uppercase;"><strong><h3>Order summary</h3></strong></td>
						</tr>
						<tr>
							<td ><strong>Bin type</strong></td>
							<td colspan="2" ><p >{{$binhire->name}}</p></td>
						</tr>
						<tr>
							<td ><strong>Bin size</strong></td>
							<td colspan="2" ><p >{{$binhire->size}}</p></td>
						</tr>
						<tr>
							<td ><strong>Description</strong></td>
							<td colspan="2" >
								<?php $tags = array("strong", "b");?>
								<p ><?php echo preg_replace('#<(' . implode( '|', $tags) . ')(?:[^>]+)?>.*?</\1>#s', '', $binhire->description2);?></p><br />
								<p style="color:#c40005;"><?php echo $binhire->description; ?></p>
							</td>
						</tr>
						<tr>
							<td ><strong>Bin hire price</strong></td>
							<td colspan="2" ><p >${{sprintf('%1.2f',$invoiceDetails->subtotal)}}</p></td>
						</tr>
						<tr>
							<td ><strong>Booking fee</strong></td>
							<td colspan="2"><p >${{sprintf('%1.2f',$invoiceDetails->bookingfee)}}</p></td>
						</tr>
						<tr>
							<td ><strong>GST 10% paid</strong></td>
							<td colspan="2" ><p>${{sprintf('%1.2f',$invoiceDetails->gst)}}</p></td>
						</tr>
						<tr style="background:#005343;">
							<td style="color:#fff;"><strong>Grand total</strong></td>
							<td colspan="2" style="color:#fff;"><p >${{sprintf('%1.2f',$invoiceDetails->totalServiceCharge)}}</p></td>
						</tr>
						<tr style="text-align:center">
							<td colspan="3" style="text-align:center;text-transform:uppercase;" ><strong>Payment confirmed, due amount 0 (Zero).</strong></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="table-responsive">
				<table class="table table-condensed" border="0" width="100%" cellpadding="3">
					<tr>
						<td width="50%" >
							<h3 style="text-transform:uppercase;">Supplier Details:</h3>
							<address  style="font-style:12px;">
								Business name : <i>{{$supplierdetails->name}}</i><br/>
								Contact name : <i>{{$supplierdetails->contactName}}</i><br/>
								Business hours phone number : <i>{{$supplierdetails->phonenumber}}</i><br/>
								Email: <i>{{$supplierdetails->email}}</i><br/>
							</address>
						</td>
					</tr>
				</table>
			</div>
		</body>
	</html>
<htmlpagefooter name="page-footer">
	{PAGENO}
</htmlpagefooter>