routes/web.php
	'as' => 'mixed.heavy.waste.pricing.form',
	'uses' => 'MixedHeavyWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('2/showForm/{status}/{message}',[
	'as' => 'mixed.heavy.waste.form',
	'uses' => 'MixedHeavyWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('2/editBinServicePrice', 'MixedHeavyWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('2/resetPricing/{bintype}/{binsize}', 'MixedHeavyWaste@resetRates')->middleware('checkRole:1,2');

/****** CLEAN FILLS SCHEDULE ***/
Route::get('/clean_fills_schedule', 'CleanFills@index')->middleware('checkRole:1,2');

Route::get('/clean_fills_schedule/{status}/{message}',[
	'as' => 'clean.fills.schedule',
	'uses' => 'CleanFills@showResult'
])->middleware('checkRole:1,2');

Route::get('3/calendarOffset/{offset}',[
	'uses' => 'CleanFills@showResult'
])->middleware('checkRole:1,2');

Route::get('3/{binsize}/calendarOffset/{offset}',[
	'uses' => 'CleanFills@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/3', 'CleanFills@editMiscDetail')->middleware('checkRole:1,2');
Route::post('3/editNonDeliveryDays', 'CleanFills@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('3/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'clean.fills.pricing.form',
	'uses' => 'CleanFills@showForm'
])->middleware('checkRole:1,2');

Route::get('3/showForm/{status}/{message}',[
	'as' => 'clean.fills.waste.form',
	'uses' => 'CleanFills@showFormResult'
])->middleware('checkRole:1,2');

Route::post('3/editBinServicePrice', 'CleanFills@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('3/resetPricing/{bintype}/{binsize}', 'CleanFills@resetRates')->middleware('checkRole:1,2');

/****** GREEN WASTE SCHEDULE ***/
Route::get('/green_waste_schedule',  [
	'as' => 'green_waste',
	'uses' => 'GreenWaste@index'
])->middleware('checkRole:1,2');

Route::get('/green_waste_schedule/{status}/{message}',[
	'as' => 'green.waste.schedule',
	'uses' => 'GreenWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('4/calendarOffset/{offset}',[
	'uses' => 'GreenWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('4/{binsize}/calendarOffset/{offset}',[
	'uses' => 'GreenWaste@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/4', 'GreenWaste@editMiscDetail')->middleware('checkRole:1,2');
Route::post('4/editNonDeliveryDays', 'GreenWaste@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('4/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'green.waste.pricing.form',
	'uses' => 'GreenWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('4/showForm/{status}/{message}',[
	'as' => 'green.waste.form',
	'uses' => 'GreenWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('4/editBinServicePrice', 'GreenWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('4/resetPricing/{bintype}/{binsize}', 'GreenWaste@resetRates')->middleware('checkRole:1,2');

/****** DIRT WASTE SCHEDULE ***/
Route::get('/dirt_waste_schedule', [
	'as' => 'dirt_waste',
	'uses' => 'DirtWaste@index'
])->middleware('checkRole:1,2');

Route::get('/dirt_waste_schedule/{status}/{message}',[
	'as' => 'dirt.waste.schedule',
	'uses' => 'DirtWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('5/calendarOffset/{offset}',[
	'uses' => 'DirtWaste@showResult'
])->middleware('checkRole:1,2');

Route::get('5/{binsize}/calendarOffset/{offset}',[
	'uses' => 'DirtWaste@showForm'
])->middleware('checkRole:1,2');


Route::post('/editMiscDetails/5', 'DirtWaste@editMiscDetail')->middleware('checkRole:1,2');
Route::post('5/editNonDeliveryDays', 'DirtWaste@editNonDeliveryDays')->middleware('checkRole:1,2');

Route::get('5/showEditPricingForm/{bintype}/{binsize}',[
	'as' => 'dirt.waste.pricing.form',
	'uses' => 'DirtWaste@showForm'
])->middleware('checkRole:1,2');

Route::get('5/showForm/{status}/{message}',[
	'as' => 'dirt.waste.form',
	'uses' => 'DirtWaste@showFormResult'
])->middleware('checkRole:1,2');

Route::post('5/editBinServicePrice', 'DirtWaste@editBinServicePrice')->middleware('checkRole:1,2');
Route::delete('5/resetPricing/{bintype}/{binsize}', 'DirtWaste@resetRates')->middleware('checkRole:1,2');

/****** ORDER RECEIPTING  ***/
Route::get('/order_receipt', [
	'as' => 'order.receipt',
	'uses' => 'ReceiptOrder@index'
])->middleware('checkRole:1,2');

Route::get('manage_order/','adminController@manage_order_view')->name('supplier_supplies')->middleware('checkRole:1');
Route::get('all_supplier_order/','adminController@all_order_view')->name('all_supplier_supplies')->middleware('checkRole:1');
Route::get('all_supplier_order_date/','adminController@all_order_view_date')->name('all_supplier_supplies_date')->middleware('checkRole:1');
Route::get('/manage_order/{idSupplier}',[
	'as' => 'supplier_supplies_result',
	'uses' => 'adminController@fetch_supplier_order_status'
])->middleware('checkRole:1');
Route::post('see_supplies_by_supplier/','adminController@fetch_supplier_order')->name('fetch_all_order_supplies')->middleware('checkRole:1');
Route::post('see_supplies_all/','adminController@fetch_all_supplier')->name('fetch_all_supplier')->middleware('checkRole:1');
Route::post('see_supplies_all_order_date/','adminController@fetch_all_supplier_order')->name('fetch_all_supplier_date')->middleware('checkRole:1');
Route::post('change_order_status/', 'adminController@update_order_status')->name('update_order_status')->middleware('checkRole:1,2');

Route::post('change_order_status_by_user/', 'ReceiptOrder@update_order_status')->name('update_order_status_by_user')->middleware('checkRole:1,2');

Route::get('order_detail/{orderref}/{idSupplier}/{idCustomer}/{idBinType}/{idBinService}','adminController@order_detail')->name('detailed_order')->middleware('checkRole:1,2');

/*** PAYPAL ***/
//Route::get('paymentdetails/{idpaymenttemp}','PaypalController@addPayment')->name('addPayment');
//Route::post('paypal', 'PaypalController@postPaymentWithpaypal')->name('paypal');
//Route::get('paypal','PaypalController@getPaymentStatus')->name('status');
//Route::get('paymentstatus','PaypalController@paymentStatus')->name('paymentstatus');
//Route::get('away','PaypalController@away')->name('away');
Route::get('paymentdetails/{idpaymenttemp}','scnpayment@addPayment')->name('addPayment');
Route::post('payment', 'scnpayment@post_details')->name('payment');
Route::get('paymenthost','scnpayment@scn_iframe')->name('host');
Route::get('payment_engagement/','scnpayment@scn_iframe_response')->name('engagement');
Route::get('payment_status/','scnpayment@paymentStatus')->name('payment_status');
Route::post('ajax_hash_post/','scnpayment@ajax_hash_post')->name('ajax_hash_post');
Route::get('away','scnpayment@away')->name('away');

/** INVOICE **/
Route::get('orderservice/{idorderservice}','ReceiptOrder@orderservicedetail')->name('orderdetails')->middleware('checkRole:1,2');
Route::get('test_invoice_mail/{idorderservice}','ReceiptOrder@test_mail')->name('test_mail')->middleware('checkRole:1,2');
Route::get('export/pdf/{idorderservice}','ReceiptOrder@pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');
Route::get('export/invoice/pdf/{idorderservice}','ReceiptOrder@invoice_pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');

/** ADMIN SUPER POWER TECHNIQUE **/
Route::get('manage_user/','adminController@usermanagement_view')->name('user_management')->middleware('checkRole:1');
Route::get('approve_user/{idUser}','adminController@aprroveuser')->name('approve_user')->middleware('checkRole:1');

Route::get('active_user/','adminController@activeuser_view')->name('active_user')->middleware('checkRole:1');
Route::get('kick_user/{idUser}','adminController@kickuser')->name('kick_user')->middleware('checkRole:1');

Route::get('banned_user/','adminController@banuser_view')->name('banned_user')->middleware('checkRole:1');
Route::get('reactivate_user/{idUser}','adminController@reactivate_user')->name('reactivate_user')->middleware('checkRole:1');

Route::prefix('booking-fees')
	->name('booking-fees.')
	->middleware('checkRole:1')
	->group(function () {

		Route::get('/', 'BookingFeeSettingController@index')
			->name('index');

		Route::get('/edit/{tblsupplier}', 'BookingFeeSettingController@edit')
			->name('edit');

		Route::post('/update/{tblsupplier}', 'BookingFeeSettingController@update')
			->name('update');

	});

/** only for jims
Route::get('approve_user/jim/{idUser}','adminController@jimapprove')->name('jimapprove')->middleware('checkRole:1');**/
/** SUMMARY **/
Route::get('manage_summary/','orderSummary@ordersummary_view')->name('summary_management')->middleware('checkRole:1');
Route::post('see_supplies_by_supplier_summary/','orderSummary@fetch_supplier_order')->name('fetch_all_order_supplies_summary')->middleware('checkRole:1');
Route::get('order_summary/export/pdf/{idSupplier}/{startDate}/{endDate}','orderSummary@pdfexporter')->name('pdfexporter')->middleware('checkRole:1,2');
Route::post('order_summary_selected/export/pdf/','orderSummary@pdfexporterselected')->name('pdfexporterselected')->middleware('checkRole:1,2');

/** BOOKING FEE **/
Route::get('booking_fee/','bookingprice@index')->name('bookingfee')->middleware('checkRole:1');
Route::get('booking_fee/{idBookingPrice}','bookingprice@edit_form')->name('edit_form')->middleware('checkRole:1');
Route::get('booking_form/','bookingprice@bookingform_view')->name('booking_form')->middleware('checkRole:1');
Route::post('edit_bookingfee/','bookingprice@edit_bookingfee')->name('edit_bookingfee')->middleware('checkRole:1');

/** MAILING EXTENSION **/
//user_registration
Route::get('mail/user/verify/{name}/{verification_code}','loginController@mail_extension')->name('mail_extension');

/** Report addiction **/
Route::get('binorder_report/','Order_Summary_BinType@order_summary_bin_view')->name('binorder_report')->middleware('checkRole:1');

/* generate payment link based on fake order */
Route::get('test-payment', 'TestPaymentController')

resources/views/booking-fee/edit.blade.php
@extends('template')
@section('content')
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xl-12">
							<div class="breadcrumb-holder">
								<h1 class="main-title float-left">Suppliers' Fee</h1>
                                <ol class="breadcrumb float-right">
									<li class="breadcrumb-item"><a href="/instructions">Home</a></li>
                                    <li class="breadcrumb-item"><a href="{{ route('booking-fees.index') }}">All Suppliers' Fee</a></li>
									<li class="breadcrumb-item active">{{ $supplier->name }}</li>
								</ol>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div class="card mb-3 mt-2">
								<div class="card-header">
									Set Supplier Fee
								</div>

								<div class="card-body">
									<div class="row">
                                        <div class="col-md-4">
                                            <form method="post" action="{{ route('booking-fees.update', [ 'tblsupplier' => $supplier ]) }}">
                                                {{ csrf_field() }}

                                                <div class="form-group">
                                                    <label>Supplier</label>
                                                    <input type="text" readonly class="form-control-plaintext" value="{{ $supplier->name }}">
                                                </div>

												<div class="form-group">
                                                    <label>Username</label>
                                                    <input type="text" readonly class="form-control-plaintext" value="{{ $supplier->user->username }}">
                                                </div>

                                                <div class="form-group">
                                                    <label>Fee</label>
                                                    <div class="input-group">
                                                        <input type="text" name="amount" class="form-control" value="{{ old('amount', @$supplier->bookingFee->amount) }}">
                                                        <div class="input-group-prepend">
                                                            <select name="type" class="form-control">
                                                                <option value="percent" {{ old('amount', @$supplier->bookingFee->type) == 'percent' ? 'selected' : '' }}>% (percentage)</option>
                                                                <option value="fix" {{ old('amount', @$supplier->bookingFee->type) == 'fix' ? 'selected' : '' }}>AUD</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>

                                                <button type="submit" class="btn btn-primary">Submit</button>

                                            </form>
                                        </div>
                                    </div>
								</div>
							</div><!-- end card-->
						</div>
					</div>
				</div>
			</div>
		</div>
@endsection

resources/views/booking-fee/index.blade.php
@extends('template')
@section('content')
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xl-12">
							<div class="breadcrumb-holder">
								<h1 class="main-title float-left">Suppliers' Fee</h1>
                                <ol class="breadcrumb float-right">
									<li class="breadcrumb-item"><a href="/instructions">Home</a></li>
									<li class="breadcrumb-item active">All Suppliers' Fee</li>
								</ol>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							@if (!empty(session('status')))
								@if (session('status') == 'danger')
									<div class="alert alert-danger" role="alert">
											{{session('message')}} <br />
									</div>
								@elseif (session('status') == 'success')
									<div class="alert alert-success" role="alert">
											{{session('message')}} <br />

									</div>
								@endif
							@endif

						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div class="card mb-3 mt-2">
								<div class="card-header">
									Active
								</div>

								<div class="card-body">
									@if (count($suppliers) > 0)
										<div class="alert alert-info" role="alert">
											The supplier list below only for approved suppliers. You need to approve supplier before set the fee.<br />
											To approve supplier, <a href="{{ route('user_management') }}">please go to this page</a>.
										</div>

										<div class="table-responsive">
											<table class="table table-bordered table-hover">
												<thead>
                                                    <th></th>
													<th>Supplier Name</th>
                                                    <th>User Name</th>
													<th>Fee</th>
													<th>Supplier Contact Name</th>
													<th>Supplier Email</th>
													<th>Supplier Phone Number</th>
												</thead>
												<tbody>
													@foreach($suppliers as $supplier)
														<tr>
                                                            <td>
                                                                <a class="btn btn-success btn-sm" href="{{ route('booking-fees.edit', [ 'tblsupplier' => $supplier ]) }}">Update</a>
															</td>
															<td>{{ $supplier->name }}</td>
                                                            <td>{{ $supplier->user->username }}</td>
															<td>
                                                                @if (!empty($supplier->bookingFee))
                                                                    {{ $supplier->bookingFee->amount }}
                                                                    {{ ($supplier->bookingFee->type == 'fix') ? 'AUD' : '%' }}
                                                                @else
                                                                    Not set
                                                                @endif
                                                            </td>
															<td>{{ $supplier->contactName }}</td>
															<td>{{ $supplier->email }}</td>
															<td>{{ $supplier->phonenumber }}</td>
														</tr>
													@endforeach
												</tbody>
											</table>
										</div>
									@else
										<p>No banned user list</p>
									@endif
								</div>
							</div><!-- end card-->
						</div>
					</div>
				</div>
			</div>
		</div>
@endsection